=== nguyenkevin-dotcom/xml_gym_guide/xml semestralniprace(1)/treninkovyPlan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:nguyen:treninkovyPlan"
    xmlns="urn:nguyen:treninkovyPlan" xmlns:t="urn:nguyen:treninkovyPlan"
    elementFormDefault="qualified">

    <xs:element name="trainingPlan" type="trainingPlanType"> 
        <xs:key name="unique_personKey">
            <xs:selector xpath="t:person"/>
            <xs:field xpath="@oid"/>
        </xs:key>
        
        <xs:key name="unique_planKey">
            <xs:selector xpath="t:plan"/>
            <xs:field xpath="@pid"/>
        </xs:key>
        
        <xs:key name="unique_date">
            <xs:selector xpath="t:plan/t:day/date"/>
            <xs:field xpath="@date"/>
        </xs:key>
        
        <xs:key name="unique_plan_nameKey">
            <xs:selector xpath="t:plan/t:name"/>
            <xs:field xpath="."/>
        </xs:key>
      
        
        <xs:key name="givenPlanKey">
            <xs:selector xpath="t:person/t:givenPlan/t:name"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        
        <xs:keyref refer="unique_plan_nameKey" name="planToPerson">
            <xs:selector xpath="t:person/t:givenPlan/t:name"/>
            <xs:field xpath="."/>
        </xs:keyref>
        
    </xs:element>
        
    <xs:complexType name="trainingPlanType">
        <xs:sequence>
            <xs:element name="person" type="personType" minOccurs="1" maxOccurs="10"/>
            <xs:element name="plan" type="planType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personType">
        <xs:sequence>
            <xs:element name="forename" type="nonEmptyString"/>
            <xs:element name="surname" type="nonEmptyString"/>
            <xs:element name="age" type="ageType"/>
            <xs:element name="height" type="xs:nonNegativeInteger"/>
            <xs:element name="weight" type="xs:nonNegativeInteger"/>
            <xs:element name="goal" type="nonEmptyString"/>
            <xs:element name="profession" type="professionType"/>
            <xs:element name="frequencyInAWeek" type="frequencyInAWeekType"/>
            <xs:element name="experience" type="floatNonNegative"/>
            <xs:element name="givenPlan" type="plansType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="oid" type="xs:int" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="plansType">
       <xs:sequence>
           <xs:element name="name" type="nonEmptyString"/>
       </xs:sequence>
    </xs:complexType>

    <xs:complexType name="planType">
        <xs:complexContent>
            <xs:extension base="plansType">
                <xs:sequence>
                    <xs:element name="start" type="dateType" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="end" type="dateType" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="day" type="dayType" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="pid" type="xs:int" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="dayType">
        <xs:sequence>
            <xs:element name="training" type="trainingType" minOccurs="0"/>
            <xs:element name="rest" type="nonEmptyString" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required"/>
    </xs:complexType>


    <xs:complexType name="trainingType">
        <xs:sequence>
            <xs:element name="exercise" type="exerciseType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="cardio" type="cardioType"/>
            <xs:element name="summary" type="summaryType"/>
        </xs:sequence>
        <xs:attribute name="split" type="splitType" use="required"/>
    </xs:complexType>

    <xs:complexType name="exerciseType">
        <xs:sequence>
            <xs:element name="name" type="nonEmptyString"/>
            <xs:element name="exercisePhoto" type="photoType"/>
            <xs:element name="muscles" type="nonEmptyString"/>
            <xs:element name="musclesPhoto" type="photoType"/>
            <xs:element name="warmUp" type="setType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="topSet" type="setType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="backOffSet" type="setType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="cid" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="cardioType">
        <xs:sequence>
            <xs:element name="name" type="nonEmptyString"/>
            <xs:element name="exercisePhoto" type="photoType"/>
            <xs:element name="period" type="xs:nonNegativeInteger"/>
            <xs:element name="speed" type="xs:float"/>
            <xs:element name="incline" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="summaryType">
        <xs:sequence>
            <xs:element name="estimatedTime" type="floatNonNegative"/>
            <xs:element name="quantity" type="xs:nonNegativeInteger"/>
            <xs:element name="primaryMuscle" type="nonEmptyString" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="musclesTargetedPhoto" type="photoType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="setType">
        <xs:sequence>
            <xs:element name="series" type="seriesType"/>
            <xs:element name="reps" type="repsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="professionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="student"/>
            <xs:enumeration value="employed"/>
            <xs:enumeration value="unemployed"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="frequencyInAWeekType">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="1"/>
            <xs:maxExclusive value="7"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="splitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="push"/>
            <xs:enumeration value="pull"/>
            <xs:enumeration value="legs"/>
            <xs:enumeration value="mixed"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="seriesType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dateType">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="2024-01-01"/>
            <xs:maxInclusive value="2024-12-12"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ageType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="repsType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="4"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:complexType name="photoType">
        <xs:attribute name="src" type="srcType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="srcType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9/_-]{1,})\.(jpg|png)"/>    
        </xs:restriction>              
    </xs:simpleType>
    
    <xs:simpleType name="floatNonNegative">
        <xs:restriction base="xs:float">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>










</xs:schema>

=== nguyenkevin-dotcom/xml_gym_guide/xml semestralniprace(1)/treninkovyPlan.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="treninkovyPlan.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<trainingPlan xmlns="urn:nguyen:treninkovyPlan"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:nguyen:treninkovyPlan treninkovyPlan.xsd">
    <person oid="1">
        <forename>Kevin</forename>
        <surname>Nguyen</surname>
        <age>20</age>
        <height>176</height>
        <weight>82</weight>
        <goal>lower body and maintain muscle mass</goal>
        <profession>student</profession>
        <frequencyInAWeek>6</frequencyInAWeek>
        <experience>1</experience>
        <givenPlan>
            <name>Le Mans</name>
        </givenPlan>
    </person>
    <person oid="2">
        <forename>Mark</forename>
        <surname>Kowalski</surname>
        <age>24</age>
        <height>172</height>
        <weight>68</weight>
        <goal>stay healthy</goal>
        <profession>employed</profession>
        <frequencyInAWeek>3</frequencyInAWeek>
        <experience>0.1</experience>
        <givenPlan>
            <name>Monaka</name>
        </givenPlan>
    </person>
    <plan pid="1">
        <name>Le Mans</name>
        <start>2024-04-29</start>
        <end>2024-05-05</end>
        <day date="2024-04-29">
            <training split="push">
                <exercise cid="1">
                    <name>Cable Lateral Raise</name>
                    <exercisePhoto src="exercises/cable_lateral_raise.png"/>
                    <muscles>Lateral Deltoid</muscles>
                    <musclesPhoto src="muscles/cable_lateral_raise.png"/>
                    <warmUp>
                        <series>2</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="2">
                    <name>Dumbbell Shoulder Press</name>
                    <exercisePhoto src="exercises/dumbbell_shoulder_press.png"/>
                    <muscles>Front Deltoid</muscles>
                    <musclesPhoto src="muscles/dumbbell_shoulder_press.png"/>
                    <warmUp>
                        <series>1</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="3">
                    <name>Dumbbell Rear Delt Fly</name>
                    <exercisePhoto src="exercises/dumbbell_rear_delt_fly.png"/>
                    <muscles>Rear Deltoid</muscles>
                    <musclesPhoto src="muscles/dumbbell_rear_delt_fly.png"/>
                    <warmUp>
                        <series>1</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="4">
                    <name>Smith Machine Incline Bench Press</name>
                    <exercisePhoto src="exercises/smith_machine_incline_bench_press.png"/>
                    <muscles>Upper Chest</muscles>
                    <musclesPhoto src="muscles/smith_machine_incline_bench_press.png"/>
                    <warmUp>
                        <series>3</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="5">
                    <name>Dumbbell Bench Press</name>
                    <exercisePhoto src="exercises/dumbbell_bench_press.png"/>
                    <muscles>Chest</muscles>
                    <musclesPhoto src="muscles/dumbbell_bench_press.png"/>
                    <warmUp>
                        <series>1</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="6">
                    <name>Cable Chest Fly</name>
                    <exercisePhoto src="exercises/cable_chest_fly.png"/>
                    <muscles>Chest</muscles>
                    <musclesPhoto src="muscles/cable_chest_fly.png"/>
                    <warmUp>
                        <series>1</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="7">
                    <name>Tricep Pushdown</name>
                    <exercisePhoto src="exercises/tricep_pushdown.png"/>
                    <muscles>Triceps</muscles>
                    <musclesPhoto src="muscles/tricep_pushdown.png"/>
                    <warmUp>
                        <series>2</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="8">
                    <name>Overhead Tricep Extension Machine</name>
                    <exercisePhoto src="exercises/overhead_tricep_extension_machine.png"/>
                    <muscles>Triceps</muscles>
                    <musclesPhoto src="muscles/overhead_tricep_extension_machine.png"/>
                    <warmUp>
                        <series>2</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <cardio>
                    <name>Treadmill Incline Walking</name>
                    <exercisePhoto src="exercises/treadmill_incline_walking.png"/>
                    <period>20</period>
                    <speed>5.5</speed>
                    <incline>10</incline>
                </cardio>
                <summary>
                    <estimatedTime>2</estimatedTime>
                    <quantity>8</quantity>
                    <primaryMuscle>Lateral Deltoid,</primaryMuscle>
                    <primaryMuscle>Front Deltoid,</primaryMuscle>
                    <primaryMuscle>Rear Deltoid,</primaryMuscle>
                    <primaryMuscle>Upper Chest,</primaryMuscle>
                    <primaryMuscle>Chest,</primaryMuscle>
                    <primaryMuscle>Triceps</primaryMuscle>
                    <musclesTargetedPhoto src="muscles/split_push.png"/>
                </summary>
            </training>
        </day>
        <day date="2024-04-30">
            <training split="pull">
                <exercise cid="9">
                    <name>Lat Pulldown Machine</name>
                    <exercisePhoto src="exercises/lat_pulldown_machine.png"/>
                    <muscles>Lats</muscles>
                    <musclesPhoto src="muscles/lat_pulldown_machine.png"/>
                    <warmUp>
                        <series>2</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="10">
                    <name>Barbell Row</name>
                    <exercisePhoto src="exercises/barbell_row.png"/>
                    <muscles>Lats, Trapezius</muscles>
                    <musclesPhoto src="muscles/barbell_row.png"/>
                    <warmUp>
                        <series>1</series>
                        <reps>10</reps>
                    </warmUp>
                    <topSet>
                        <series>1</series>
                        <reps>10</reps>
                    </topSet>
                    <backOffSet>
                        <series>1</series>
                        <reps>10</reps>
                    </backOffSet>
                </exercise>
                <exercise cid="11">
